version: '3.4'
services:
  mariadb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courseman
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    restart: on-failure
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  data:
